# Generated by Django 4.1.7 on 2023-02-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=80)),
                ('typology', models.CharField(max_length=10)),
                ('titular', models.CharField(max_length=80)),
                ('inversion', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=80)),
            ],
        ),
    ]
