# Generated by Django 4.1.7 on 2023-02-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='inversion',
            new_name='investment',
        ),
    ]
