# Generated by Django 4.1.7 on 2023-02-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='typology',
            field=models.CharField(max_length=20),
        ),
    ]
