# Generated by Django 4.1.7 on 2023-02-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('href', models.CharField(max_length=120)),
                ('gbfs', models.CharField(max_length=120)),
                ('location_city', models.CharField(max_length=80)),
                ('location_country', models.CharField(max_length=80)),
                ('location_latitude', models.IntegerField()),
                ('location_longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('timestamp', models.CharField(max_length=120)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('empty_slots', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikesantiago.network')),
            ],
        ),
    ]
