# Generated by Django 4.1.7 on 2023-02-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikesantiago', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='gbfs',
            new_name='gbfs_href',
        ),
    ]
