# Generated by Django 4.1.7 on 2023-02-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikesantiago', '0002_rename_gbfs_network_gbfs_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='author',
            new_name='network',
        ),
    ]
